M48
; DRILL file KiCad 10.0.6 date 2026-10-08T18:15:19
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-08T18:15:19-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X234.432Y-94.465
X234.432Y-99.315
T2
X237.462Y-94.165
X237.462Y-99.615
T3
X145.0Y-22.0
X145.0Y-112.0
X235.0Y-22.0
X235.0Y-112.0
M30
